# Generated by Django 3.1.6 on 2021-04-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='data_encomenda',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='data_entrega',
            field=models.DateTimeField(),
        ),
    ]
